### ISSUE TITLE
Indentation character is not configurable

### ISSUE THREAD

**Issue by brianblakely** [GoogleChrome/chromedeveditor#2729]
Editor only seems to support 2 spaces for indentations, and this size cannot be changed, nor can it be changed to tabs.

Thanks!

**Comment by lealcy** [comment]
So, where is the change?

**Comment by brianblakely** [comment]
[This product is dead.](https://plus.google.com/+SriramSaroop/posts/6EwgknwKpeS) I highly recommend Cloud9, which rivals the very best IDEs (surpasses, IMO).

https://c9.io
