### ISSUE TITLE
Make "refactor for csp" functionality available as a CLI. (was: vulcanize equivalent of 'refactor for csp'?)

### ISSUE THREAD

**Issue by davidmaxwaterman** [GoogleChrome/chromedeveditor#3584]
Can someone tell me how I might use vulcanize to do the equivalent of the 'refactor for csp' menu item. I would like to refactor the entire bower_components directory in one go.

We're developing an extension and have our entire app in app/, so can't use CDE (it ignores .bowerc, for a start).

**Comment by csrocha** [comment]
Hi everyone.

I found the following files in brower components wich break the Refactor. They are:

bower_components/marked-element/demo/index.html
bower_components/marked-element/test/marked-element.html

I had change the file type from html to htmlx and the Refactor is back to life!

**Comment by gio1135** [comment]
Boom!
