### ISSUE TITLE
JS Chrome App (Polymer paper elements) deployed to mobile = renders improperly

### ISSUE THREAD

**Issue by kenmoore** [GoogleChrome/chromedeveditor#3681]
I'm just learning about Chrome apps on mobile, and I've followed these very simple steps to get started:
- installed the Chrome Dev Tool v0.10.0 on my Android Nexus 4 and Nexus 7
- opened CDE and created a new JavaScript Chrome App (with Polymer paper elements)
  - once all bower updates were done, ran the "Refactor for CSP" on the bower_components folder
- ran Deploy to mobile, providing the IP address from my Nexus device 

I tested my N4 and N7 separately, and each one rendered the app improperly, as in the attached screenshot.  I've also attached the proper rendering as seen on my MacBook Pro.

![paper-improper](https://cloud.githubusercontent.com/assets/4031605/4894929/4141ff88-63dd-11e4-8987-93a2001c85af.png)
![paper-proper](https://cloud.githubusercontent.com/assets/4031605/4894930/4501bc4e-63dd-11e4-8bb4-92ae7231e1bf.png)

**Comment by tswast** [comment]
I am getting this same issue with a Polymer app deploying to iOS on a fresh build today.

I am seeing the same behavior as kenmoore.

"Push timed out: Total time exceeds 60 seconds"
 - the loading reaches 100% but clicking Launch no-ops
 - the loading reaches 100% and the app is apparently launched (the Launch
button becomes Stop) but there is no visible UI

**Comment by tswast** [comment]
I do seem to be able to deploy to my Nexus 6 using the fresh build, though. (11.2-dev)
