### ISSUE TITLE
[Polymer Designer] Cannot use designer at bottom-right icon

### ISSUE THREAD

**Issue by achuthhadnoor** [GoogleChrome/chromedeveditor#3752]
i cannot view anything when i click  on polymer symbol that shows polymer:designer but is nothing to do!!
please help me!

**Comment by hdf** [comment]
Same problem here. Using Chrome Dev Editor 0.19.3489 on Windows 7, and whenever I open a html file, that has webelements in it, or is one, and click on Edit in Polymer Designer, it shows an empty canvas, as if the file was not loaded. It says the file name on the upper left corner, but it says "my-element" in the upper right, no mater what file I open. If I run the project, it does work without a problem.
