### ISSUE TITLE
Is ChromeDevEditor still an active project?

### ISSUE THREAD

**Issue by donaldbraman** [GoogleChrome/chromedeveditor#3949]
Just noticing a lack of recent updates.  Summer doldrums or are you looking to hand it off to someone?  (Not trying to be snarky; just checking so I can plan accordingly.)

**Comment by rdegennaro** [comment]
I hope so.  :-)  I've just started using it.  I like it so far.  At least it fits my simple needs.

**Comment by Franzaine** [comment]
Well it is not actively being developed by Google any more but it looks like the community is trying to get it started: https://plus.google.com/+SriramSaroop/posts/6EwgknwKpeS

**Comment by donaldbraman** [comment]
Thank for the update, Franzaine.  Certainly very useful to novice users and developer, but those are also the least likely to be able to take over the development.  But here's hoping!
