### ISSUE TITLE
Chrome Dev Editor - App Name

### ISSUE THREAD

**Issue by mguh22** [GoogleChrome/chromedeveditor#4023]
Now this is no longer being actively developed, would one of you kind people please republish it to the Chrome Web Store but with the unsightly '(developer preview)' part of its name removed?

Actually, even better, could you perhaps simply just call it 'Dev Editor'; that way its full name will show up nicely within my Launcher on my Chromebook?

![launcher](https://cloud.githubusercontent.com/assets/16085452/11513484/644b2fa4-986b-11e5-884f-1b54c3c59e2b.png)

Many thanks

**Comment by gio1135** [comment]
The recipient has read this message at 2:13 PM on 12/1/2015.

On Tue, Dec 1, 2015 at 12:39 PM mguh22 <notifications@github.com> wrote:

> Now, this is no longer being actively developed, would one of you kind
> people please republish it to the Chrome Web Store but with the unsightly
> '(developer preview)' part of its name removed?
>
> Actually, even better, could you perhaps simply just call it 'Dev Editor';
> that way its full name will show up nicely within my Launcher on my
> Chromebook?
>
> [image: launcher]
> <https://cloud.githubusercontent.com/assets/16085452/11513484/644b2fa4-986b-11e5-884f-1b54c3c59e2b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/chromedeveditor/issues/4023>.
>
-- 
Giovanni Gallardo

**Comment by ussuri** [comment]
Done
