### ISSUE TITLE
How do you change the font size?

### ISSUE THREAD

**Issue by georgemck** [GoogleChrome/chromedeveditor#4028]
How do you change the font size?

**Comment by gio1135** [comment]
Click the gear icon.
[image: hrome_Dev-Gear_Icon.png]

Then, click the plus or minus sign to increase or decrease the font size.
[image: Chrome_Dev-Font-Size.png]

On Wed, Dec 9, 2015 at 11:20 AM georgemck <notifications@github.com> wrote:

> How do you change the font size?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/chromedeveditor/issues/4028>.
>
-- 
Sent from My Maz–Ruh Legitness
